In [34]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
from numpy.linalg import svd

In [40]:
#corpus
D = ['Children love stories.', 'It is true!', 'Every child enjoys it for different reasons']

#query to be searched
query = ['man love stories']

In [41]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(D)
print(vectorizer.get_feature_names())  #vocabulry in ascending order

['child', 'children', 'different', 'enjoys', 'every', 'for', 'is', 'it', 'love', 'reasons', 'stories', 'true']


In [39]:
A = X.T.toarray()
print("Term-document matrix\n",A)

Term-document matrix
 [[0 0 1]
 [1 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]]


In [42]:
#SVD of the Term-Document matrix
[u,s,vt] = svd(A, full_matrices=False)

In [43]:
#Transforming the query into a vector
q = vectorizer.transform(query)
q = q.toarray()
print(q)

[[0 0 0 0 0 0 0 0 1 0 1 0]]


In [44]:
#Finding the new query vector
q = np.matmul(np.matmul(q,u),np.linalg.inv(np.diag(s)))
print(q)

[[-3.85554631e-17 -6.66666667e-01 -2.38285866e-17]]


In [45]:
#finding the most similar document for the query vector by taking the dot product between query and 
#each column in the vt matrix and normalize them
for i in range(len(vt)):
    print(np.dot(q,vt[:,i])/(np.linalg.norm(q)*np.linalg.norm(vt[:,i])))

[1.]
[-2.14993764e-17]
[6.44981293e-17]
